name: The EARs Reviewing bot on comments

on:
  issue_comment:
    types: [created]

jobs:
  request-reviewer:
    if: contains(github.event.issue.labels.*.name, 'ERGA-BGE') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run python script to assign reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.issue.number }}
          COMMENT_TEXT: ${{ github.event.comment.body }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}

        run: |
          comment_body=$(echo "${{ github.event.comment.body }}" | tr '[:upper:]' '[:lower:]')
          if [[ "${comment_body}" =~ (yes|no) ]]; then
            python -m pip install --upgrade pip
            python -m pip install -r ear_bot/requirements.txt
            python -u ear_bot/ear_bot_reviewer.py --comment
          else
            echo "Skipping job as COMMENT TEXT is not 'YES' or 'NO'"
          fi

      - name: Uplaod csv file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "rev/*.csv"
          branch: main
